### ISSUE TITLE
Split custom resources

### ISSUE THREAD

**Issue by IanLewis** [IanLewis/memcached-operator#4]
Split custom resources into a `MemcachedProxy` resource and `MemcachedCluster` resource that can be used together. That way users can set up a memcached proxy that points to a memcached cluster that they create and maintain themselves.

The `MemcachedProxy` objects might look something like the following. That makes the definition look something like an Ingress. (prefix could be supported by mcrouter prefix routing).
```
apiVersion: "ianlewis.org/v1alpha1"
kind: "MemcachedProxy"
metadata:
  name: example-proxy
spec:
  image: "my/images/mcrouter:v1"
  rules:
    - prefix: "A"
      hash: "ch3"
      serviceName: "memcached-a"
    - prefix: "B"
      hash: "crc32"
      serviceName: "memcached-b"
    - prefix: ""
      hash: "ch3"
      serviceName: "memcached-c"
```
